import ReduxProvider from "@/redux/ReduxProvider";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/config/firebase";
import AuthContainer from "@/containers/authContainer/AuthContainer";
import ReactQueryProvider from "@/containers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // onAuthStateChanged(auth, (user) => {
  //   console.log("from layout", user);
  // });

  //   const dispatch = useDispatch();

  // const router = useRouter();

  // onAuthStateChanged(auth, (user) => {
  //   if (user) {
  //     dispatch(
  //       setCurrentUser({
  //         isLoading: false,
  //         active: true,
  //       })
  //     );
  //     router.replace("/");
  //   } else if (!user) {
  //     dispatch(
  //       setCurrentUser({
  //         isLoading: false,
  //         active: false,
  //       })
  //     );
  //     router.replace("/login");
  //   }
  // });

  return (
    <html lang="en">
      <ReduxProvider>
        <ReactQueryProvider>
          <AuthContainer>
            <body className={inter.className}>{children}</body>
          </AuthContainer>
        </ReactQueryProvider>
      </ReduxProvider>
    </html>
  );
}
